ClassicECommerceApp.Web/Controllers/HomeController.cs
using ClassicECommerceApp.Web.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ClassicECommerceApp.Web.Controllers;

[Authorize]
public class HomeController : Controller
{
	private readonly ILogger<HomeController> _logger;

	public HomeController(ILogger<HomeController> logger)
	{
		_logger = logger;
	}

	[AllowAnonymous]
	public IActionResult Index()
	{
		return View();
	}

	public IActionResult Privacy()
	{
		return View();
	}

	[AllowAnonymous]
	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	public IActionResult Error()
	{
		return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
	}
}

ClassicECommerceApp.Web/ViewComponents/ProductShowcaseViewComponent.cs
using ClassicECommerceApp.Web.Models.ViewModels;
using ClassicECommerceApp.Web.Services.Application.ProductServices;
using Microsoft.AspNetCore.Mvc;

namespace ClassicECommerceApp.Web.ViewComponents
{
    public class ProductShowcaseViewComponent : ViewComponent
    {
        private readonly IProductService _productService;

        public ProductShowcaseViewComponent(IProductService productService)
        {
            _productService = productService;
        }

        public async Task<IViewComponentResult> InvokeAsync(string title)
        {
            if (title == "Best sold products")
            {
                var products = await _productService.GetBestSoldProductsAsync();
                var viewModel = new ProductShowcaseViewModel
                {
                    Title = title,
                    Products = products
                };
                return View(viewModel);
            }
            else
            {
                var products = await _productService.GetBestSoldProductsAsync();
                var viewModel = new ProductShowcaseViewModel
                {
                    Title = title,
                    Products = products
                };
                return View(viewModel);
            }
        }
    }
}

ClassicECommerceApp.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="tw-flex tw-flex-col tw-items-center tw-justify-center tw-mt-8">
    <div class="tw-flex tw-flex-col tw-items-center tw-justify-center tw-max-w-7xl tw-mx-auto">
        <div class="tw-relative tw-w-full tw-max-w-7xl">
            <!-- Slides -->
            <div class="mySlides fade tw-hidden">
                <div class="numbertext tw-absolute tw-top-0 tw-px-3 tw-py-2 tw-text-xs tw-text-gray-200">1 / 3</div>
                <img src="https://www.w3schools.com/howto/img_nature_wide.jpg" class="tw-h-auto tw-w-128" />
                <div class="tw-absolute tw-bottom-4 tw-w-full tw-px-3 tw-py-2 tw-text-center tw-text-sm tw-text-gray-200">Caption Text</div>
            </div>

            <div class="mySlides fade tw-hidden">
                <div class="numbertext tw-absolute tw-top-0 tw-px-3 tw-py-2 tw-text-xs tw-text-gray-200">2 / 3</div>
                <img src="https://www.w3schools.com/howto/img_snow_wide.jpg" class="tw-w-128 tw-h-auto" />
                <div class="tw-absolute tw-bottom-4 tw-w-full tw-px-3 tw-py-2 tw-text-center tw-text-sm tw-text-gray-200">Caption Two</div>
            </div>

            <div class="mySlides fade tw-hidden">
                <div class="numbertext tw-absolute tw-top-0 tw-px-3 tw-py-2 tw-text-xs tw-text-gray-200">3 / 3</div>
                <img src="https://www.w3schools.com/howto/img_lights_wide.jpg" class="tw-w-128 tw-h-auto" />
                <div class="tw-absolute tw-bottom-4 tw-w-full tw-px-3 tw-py-2 tw-text-center tw-text-sm tw-text-gray-200">Caption Three</div>
            </div>

            <!-- Navigation Buttons -->
            <button class="tw-bg-opacity-80 tw-absolute tw-left-0 tw-top-1/2 tw-flex tw-h-12 tw-w-12 tw-items-center tw-justify-center tw-rounded-r-full tw-bg-gray-800 tw-text-lg tw-font-bold tw-text-white tw-transition tw-duration-500 tw-ease-in tw--mt-10 hover:tw-bg-opacity-100" onclick="plusSlides(-1)">&#10094;</button>
            <button class="tw-bg-opacity-80 tw-absolute tw-right-0 tw-top-1/2 tw-flex tw-h-12 tw-w-12 tw-items-center tw-justify-center tw-rounded-l-full tw-bg-gray-800 tw-text-lg tw-font-bold tw-text-white tw-transition tw-duration-500 tw-ease-in tw--mt-10 hover:tw-bg-opacity-100" onclick="plusSlides(1)">&#10095;</button>
        </div>

        <!-- Dots -->
        <div class="tw-text-center tw-mt-4">
            <span class="dot tw-mx-1 tw-inline-block tw-h-3 tw-w-3 tw-cursor-pointer tw-rounded-full tw-bg-gray-400 tw-transition tw-duration-500 tw-ease-in-out" onclick="currentSlide(1)"></span>
            <span class="dot tw-mx-1 tw-inline-block tw-h-3 tw-w-3 tw-cursor-pointer tw-rounded-full tw-bg-gray-400 tw-transition tw-duration-500 tw-ease-in-out" onclick="currentSlide(2)"></span>
            <span class="dot tw-mx-1 tw-inline-block tw-h-3 tw-w-3 tw-cursor-pointer tw-rounded-full tw-bg-gray-400 tw-transition tw-duration-500 tw-ease-in-out" onclick="currentSlide(3)"></span>
        </div>

    </div>

    <div class="tw-w-full">
        @await Component.InvokeAsync("ProductShowcase", new { title = "Best sold products" })
    </div>
</div>


@section Scripts {
    <script src="~/js/carousel.js"></script>
}